server:
  port: 8080

idealista:
  advertisement:
    irrelevant-score: 40
  init:
    enabled: true
  security:
    username: idealistaUser
    password: idealistaPassword
    role: USER

springdoc:
  api-docs:
    path: /api-docs
  version: '@springdoc.version@'