server:
  port: 8080

idealista:
  advertisement:
    irrelevant-score: 40
  init:
    enabled: true
  security:
    username: ${APP_USERNAME:idealistaUser}
    password: ${APP_PASSWORD:idealistaPassword}
    role: ${APP_ROLE:USER}

springdoc:
  api-docs:
    path: /api-docs
  version: '@springdoc.version@'